In [ ]:
https://drive.google.com/file/d/1vuppy3kaLDSPz9BNCKVOxaFDQflMa8Mi/view?usp=sharing

In [ ]:
1. Given a sample list, tuple with elements as numbers from 1-10. Convert each
of the data types into a pandas series. Create a separate list of index values for the
series.

In [ ]:
l=[1,2,3,4,5,6,7,8,9,10]
t=(1,2,3,4,5,6,7,8,9,10)
ind=[0,1,2,3,4,5,6,7,8,9]

In [ ]:
import pandas as pd

In [ ]:
s=pd.Series(l,index=ind)
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
s=pd.Series(t,index=ind)
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
2. Create a python dictionary with three key value pairs. Keep the keys as the first names,
and the respective last names as values in the dictionary. Use the dictionary to create a
pandas series.

In [ ]:
d={'max':'verstappen','carlos':'sainz','charles':'leclerz'}
d

{'max': 'verstappen', 'carlos': 'sainz', 'charles': 'leclerz'}

In [ ]:
s1=pd.Series(d)
s1

max        verstappen
carlos          sainz
charles       leclerz
dtype: object

In [ ]:
3. Create a pandas series, with the elements as numbers from 1-10. Use the index values
starting from 0-10. For the above series:
a. Convert it to a list.
b. Convert it to a dictionary.
c. Convert it to a tuple.
d. Convert it to a set.

In [ ]:
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
# a. Convert it to a list.
print(list(s))
print(s.to_list())
# b. Convert it to a dictionary.
print(s.to_dict())
# c. Convert it to a tuple.
print(tuple(s))
# d. Convert it to a set.
print(set(s))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10}
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [ ]:
4. Create a sample pandas series with x integer elements. Perform the following operations
on the same:
a. Print the first 5 elements of the series
b. Print the last 5 elements of the series
c. Insert an integer value ‘50’ at the index 5.
d. Update the last element in the series with the value 100.
e. Delete the first element from the series.
Note: The index values must not be affected by the operations and should be uniform for
the series after the last operation.

In [ ]:
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
# a. Print the first 5 elements of the series
s.head(5)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s[:5]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
b. Print the last 5 elements of the series

In [ ]:
s.tail()

5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
s[-5:]

5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
c. Insert an integer value ‘50’ at the index 5.

In [ ]:
#series to list
#insert
#list to series

In [ ]:
l=s.to_list()
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
l.insert(5,50)

In [ ]:
l

[1, 2, 3, 4, 5, 50, 6, 7, 8, 9, 10]

In [ ]:
s=pd.Series(l)
s

0      1
1      2
2      3
3      4
4      5
5     50
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [ ]:
#6-100
s1=s[:6]
s2=s[6:]
s3=pd.Series([100])

In [ ]:
reset_index(drop=True)-reset index
reset_index()- converts the output to dataframe

In [ ]:
s=pd.concat((s1,s3,s2)).reset_index(drop=True)
s

0       1
1       2
2       3
3       4
4       5
5      50
6     100
7       6
8       7
9       8
10      9
11     10
dtype: int64

In [ ]:
d. Update the last element in the series with the value 100.
e. Delete the first element from the series.
Note: The index values must not be affected by the operations and should be uniform for
the series after the last operation.

In [ ]:
s.iloc[11]=100

In [ ]:
#loc- labels, iloc-integer labels

In [ ]:
s

0       1
1       2
2       3
3       4
4       5
5      50
6     100
7       6
8       7
9       8
10      9
11    100
dtype: int64

In [ ]:
s.drop(0,axis=0).reset_index(drop=True)#axis=0-row label,axis=1-column label

0       2
1       3
2       4
3       5
4      50
5     100
6       6
7       7
8       8
9       9
10    100
dtype: int64

In [ ]:
def search(series,value):
  for i,j in enumerate(series):
    if j==value:
      print(f"{value} is found at index {i}")
      break
  else:
    print(f"{value} is not found")
search(s,100)

100 is found at index 6

In [ ]:
for i,j in enumerate(s):#i=index,j=value
  print(i,j)

0 1
1 2
2 3
3 4
4 5
5 50
6 100
7 6
8 7
9 8
10 9
11 100

In [ ]:
s.where(s==100)

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
6     100.0
7       NaN
8       NaN
9       NaN
10      NaN
11    100.0
dtype: float64

In [ ]:
6. For the given series A and B, perform concatenation on the same.
series_A = pd.Series([1,2,3,4,5])
series_B = pd.Series([6,7,8,9,10])
7. Using loops in python, print all the elements within a pandas series.
Sample = pd.Series([1,2,3,4,5,6,7,8,9,10])

In [ ]:
series_A = pd.Series([1,2,3,4,5])
series_B = pd.Series([6,7,8,9,10])

In [ ]:
pd.concat((series_A,series_B)).reset_index(drop=True)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
#7
Sample = pd.Series([1,2,3,4,5,6,7,8,9,10])

In [ ]:
for i in Sample:
  print(i)

1
2
3
4
5
6
7
8
9
10

In [ ]:
8. For a given nested list and a sample dictionary, create two data frames using pandas.
List = [['AA','BB','CC'], ['DD','EE','FF'], ['GG','HH','II']]
Dictionary = { 'Kris': ['Jordan', 12,22],'Memphis': ['Depay', 23, 24]}

In [ ]:
List = [['AA','BB','CC'], ['DD','EE','FF'], ['GG','HH','II']]
Dictionary = { 'Kris': ['Jordan', 12,22],'Memphis': ['Depay', 23, 24]}

In [ ]:
df1=pd.DataFrame(List)
df1

    0   1   2
0  AA  BB  CC
1  DD  EE  FF
2  GG  HH  II

In [ ]:
df2=pd.DataFrame(Dictionary)
df2

     Kris Memphis
0  Jordan   Depay
1      12      23
2      22      24

In [ ]:
9. Create a pandas Dataframe with two columns = [‘Name’, ‘Age’]. Perform the following
operations on the same.
a. Print the first 3 rows of the Data Frame .
b. Print the rows that have the age greater than 15.
c. Insert 5 imaginary names and ages as values to the pandas Data Frame .
d. Update the 5th row so that the name = john and age=56.
e. Delete the first row from the Data Frame .

In [ ]:
dict={'name':['alex','henry','john','kate','max'],'age':[18,19,12,16,29]}

In [ ]:
dict

{'name': ['alex', 'henry', 'john', 'kate', 'max'], 'age': [18, 19, 12, 16, 29]}

In [ ]:
a. Print the first 3 rows of the Data Frame .

In [ ]:
df=pd.DataFrame(dict)
df

    name  age
0   alex   18
1  henry   19
2   john   12
3   kate   16
4    max   29

In [ ]:
df.head(3)

    name  age
0   alex   18
1  henry   19
2   john   12

In [ ]:
b. Print the rows that have the age greater than 15.

In [ ]:
df[df['age']>15]

    name  age
0   alex   18
1  henry   19
3   kate   16
4    max   29

In [ ]:
c. Insert 5 imaginary names and ages as values to the pandas Data Frame .

In [ ]:
df2=pd.DataFrame({'name': ['Frank', 'Grace', 'Hannah', 'Ian', 'Jack'], 'age': [30, 40, 50, 60, 70]})

In [ ]:
df2

     name  age
0   Frank   30
1   Grace   40
2  Hannah   50
3     Ian   60
4    Jack   70

In [ ]:
new_df=pd.concat((df,df2)).reset_index(drop=True)

In [ ]:
new_df

     name  age
0    alex   18
1   henry   19
2    john   12
3    kate   16
4     max   29
5   Frank   30
6   Grace   40
7  Hannah   50
8     Ian   60
9    Jack   70

In [ ]:
d. Update the 5th row so that the name = john and age=56.
e. Delete the first row from the Data Frame .

In [ ]:
new_df.iloc[5]={'name':'john','age':'56'}

<ipython-input-112-83c64e9cdb74>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '56' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  new_df.iloc[5]={'name':'john','age':'56'}

In [ ]:
new_df

     name age
0    alex  18
1   henry  19
2    john  12
3    kate  16
4     max  29
5    john  56
6   Grace  40
7  Hannah  50
8     Ian  60
9    Jack  70

In [ ]:
new_df.drop(0).reset_index(drop=True)

     name age
0   henry  19
1    john  12
2    kate  16
3     max  29
4    john  56
5   Grace  40
6  Hannah  50
7     Ian  60
8    Jack  70

In [ ]:
10. For the Data Frame obtained from step 9, convert the same to a list and a dictionary
respectively.

In [ ]:
new_df.values.tolist()

[['alex', 18],
 ['henry', 19],
 ['john', 12],
 ['kate', 16],
 ['max', 29],
 ['john', '56'],
 ['Grace', 40],
 ['Hannah', 50],
 ['Ian', 60],
 ['Jack', 70]]

In [ ]:
new_df.to_dict()

{'name': {0: 'alex',
  1: 'henry',
  2: 'john',
  3: 'kate',
  4: 'max',
  5: 'john',
  6: 'Grace',
  7: 'Hannah',
  8: 'Ian',
  9: 'Jack'},
 'age': {0: 18,
  1: 19,
  2: 12,
  3: 16,
  4: 29,
  5: '56',
  6: 40,
  7: 50,
  8: 60,
  9: 70}}

In [ ]:
11. Create two separate Data Frame s A and B, and perform the following operations on
them.
a. Concatenate the two Data Frame s to a new Data Frame C.
b. Split the Data Frame C row wise.
c. Split the Data Frame column wise based on a condition. For example - columns
values greater than 10, column values less than 10, etc.

In [ ]:
12. Create a Data Frame with columns Name and Age. Perform the following operations.
a. Write a sample code to search for the Name/Names where Age is 20.
b. Sort the Data Frame in ascending order of ages.
c. Using Python loops, print the ages from the data frame and store it in a set.

In [ ]:
#Groupby function()


country state     unemployement_rate
india   karnataka   8.0%
india   tamil nadu  8.2%
india   punjab      12%
USA     neveda      5.2%
USA     ohio        8.2%

In [ ]:
df.groupby(['column name',....]).aggregation()

In [ ]:
#aggregation- sum(), count(),size(),mean,median,mode,min(),max,std,var,idxmax...

In [ ]:
df=pd.read_csv('/content/US_honey_dataset (3).csv')

In [ ]:
df

,Unnamed: 0,state,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
0,0,Alabama,16000,58,928000,28000,62.00,575000,1995
1,1,Arizona,52000,79,4108000,986000,68.00,2793000,1995
2,2,Arkansas,50000,60,3000000,900000,64.00,1920000,1995
3,3,California,420000,93,39060000,4687000,60.00,23436000,1995
4,4,Colorado,45000,60,2700000,1404000,68.00,1836000,1995
...,...,...,...,...,...,...,...,...,...
1110,1110,Virginia,6000,40,79000,79000,8.23,1975000,2021
1111,1111,Washington,96000,32,1206000,1206000,2.52,7741000,2021
1112,1112,WestVirginia,6000,43,136000,136000,4.80,1238000,2021
1113,1113,Wisconsin,42000,47,750000,750000,2.81,5547000,2021
1114,1114,Wyoming,38000,58,242000,242000,2.07,4562000,2021

In [ ]:
df[df['state']=='Alabama']

,Unnamed: 0,state,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
0,0,Alabama,16000,58,928000,28000,62.00,575000,1995
44,44,Alabama,16000,64,1024000,102000,86.00,881000,1996
88,88,Alabama,14000,66,924000,92000,81.00,748000,1997
131,131,Alabama,16000,71,1136000,159000,72.00,818000,1998
174,174,Alabama,17000,68,1156000,185000,56.00,647000,1999
217,217,Alabama,16000,78,1248000,187000,59.00,736000,2000
260,260,Alabama,14000,73,1022000,235000,71.00,726000,2001
303,303,Alabama,12000,86,1032000,103000,111.00,1146000,2002
347,347,Alabama,13000,82,1066000,43000,126.00,1343000,2003
391,391,Alabama,12000,87,1044000,282000,140.00,1462000,2004
431,431,Alabama,13000,66,858000,266000,128.00,1098000,2005
472,472,Alabama,11000,72,792000,230000,146.00,1156000,2006
513,513,Alabama,11000,56,616000,209000,141.00,869000,2007
554,554,Alabama,9000,66,594000,214000,186.00,1105000,2008
595,595,Alabama,9000,49,441000,66000,182.00,803000,2009
636,636,Alabama,9000,54,73000,73000,240.00,1166000,2010
676,676,Alabama,9000,50,63000,63000,251.00,1130000,2011
716,716,Alabama,8000,54,65000,65000,247.00,1067000,2012
756,756,Alabama,7000,52,55000,55000,285.00,1037000,2013
795,795,Alabama,7000,53,26000,26000,353.00,1310000,2014
835,835,Alabama,7000,47,13000,13000,383.00,1260000,2015
875,875,Alabama,7000,52,33000,33000,345.00,1256000,2016
915,915,Alabama,7000,45,22000,22000,288.00,907000,2017
955,955,Alabama,6000,45,14000,14000,3.72,1004000,2018
995,995,Alabama,7000,42,44000,44000,3.38,994000,2019
1035,1035,Alabama,7000,39,66000,66000,5.52,1507000,2020
1075,1075,Alabama,8000,40,112000,112000,5.99,1917000,2021

In [ ]:
df['state'].unique()

array(['Alabama', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'NewJersey', 'NewMexico', 'NewYork',
       'NorthCarolina', 'NorthDakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'SouthCarolina', 'SouthDakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'WestVirginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [ ]:
df.groupby('state').size().reset_index(name='count')

            state  count
0         Alabama     27
1         Arizona     27
2        Arkansas     27
3      California     27
4        Colorado     27
5         Florida     27
6         Georgia     27
7          Hawaii     27
8           Idaho     27
9        Illinois     27
10        Indiana     27
11           Iowa     27
12         Kansas     27
13       Kentucky     26
14      Louisiana     27
15          Maine     27
16       Maryland      9
17       Michigan     27
18      Minnesota     27
19    Mississippi     27
20       Missouri     27
21        Montana     27
22       Nebraska     27
23         Nevada     15
24      NewJersey     27
25      NewMexico     18
26        NewYork     27
27  NorthCarolina     27
28    NorthDakota     27
29           Ohio     27
30       Oklahoma      9
31         Oregon     27
32   Pennsylvania     27
33  SouthCarolina     12
34    SouthDakota     27
35      Tennessee     27
36          Texas     27
37           Utah     27
38        Vermont     27
39       Virginia     27
40     Washington     27
41   WestVirginia     27
42      Wisconsin     27
43        Wyoming     27

In [ ]:
#value_counts()
df['state'].value_counts()

state
Alabama          27
Missouri         27
Arizona          27
NewJersey        27
NewYork          27
NorthCarolina    27
NorthDakota      27
Ohio             27
Oregon           27
Pennsylvania     27
SouthDakota      27
Tennessee        27
Texas            27
Utah             27
Vermont          27
Virginia         27
Washington       27
WestVirginia     27
Wisconsin        27
Montana          27
Nebraska         27
Mississippi      27
Minnesota        27
Arkansas         27
California       27
Colorado         27
Florida          27
Georgia          27
Hawaii           27
Idaho            27
Illinois         27
Indiana          27
Iowa             27
Kansas           27
Louisiana        27
Maine            27
Michigan         27
Wyoming          27
Kentucky         26
NewMexico        18
Nevada           15
SouthCarolina    12
Oklahoma          9
Maryland          9
Name: count, dtype: int64

In [ ]:
df.columns

Index(['Unnamed: 0', 'state', 'colonies_number', 'yield_per_colony',
       'production', 'stocks', 'average_price', 'value_of_production', 'year'],
      dtype='object')

In [ ]:
df.groupby(['state','year']).mean().sort_values('colonies_number',ascending=False).reset_index()

,state,year,Unnamed: 0,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production
0,NorthDakota,2018,980.0,550000.0,72.0,4752000.0,4752000.0,1.87,74052000.0
1,NorthDakota,2019,1020.0,520000.0,65.0,6422000.0,6422000.0,1.43,48334000.0
2,NorthDakota,2021,1100.0,515000.0,55.0,2266000.0,2266000.0,2.19,62032000.0
3,NorthDakota,2010,662.0,510000.0,91.0,12995000.0,12995000.0,150.00,69615000.0
4,California,1999,177.0,505000.0,60.0,30300000.0,10302000.0,53.00,16059000.0
...,...,...,...,...,...,...,...,...,...
1110,Kentucky,2001,273.0,3000.0,78.0,234000.0,94000.0,131.00,307000.0
1111,Kentucky,2002,316.0,3000.0,54.0,162000.0,47000.0,165.00,267000.0
1112,Vermont,2013,789.0,3000.0,51.0,46000.0,46000.0,389.00,595000.0
1113,Kentucky,2013,769.0,3000.0,41.0,17000.0,17000.0,325.00,400000.0
1114,Maryland,2003,363.0,2000.0,42.0,84000.0,21000.0,191.00,160000.0

In [2]:
import shutil

src = "/content/drive/MyDrive/Colab Notebooks/_Pandas_handson_23_2.ipynb"
dest = "/content/Data_Science_-_AI_ML/_Pandas_handson_23_2.ipynb"

shutil.copy(src, dest)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).